# Generated by Django 4.2 on 2023-05-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tigela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.IntegerField(choices=[(150, '150ml'), (200, '200ml'), (300, '300ml'), (400, '400ml'), (500, '500ml'), (1000, '1L')])),
                ('tipo', models.CharField(choices=[('P', 'Plastico'), ('L', 'Lousa'), ('B', 'Biscoito/Casquinha')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sorvete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('estoque', models.IntegerField()),
                ('preco', models.FloatField()),
                ('ingredientes', models.ManyToManyField(to='polls.ingredientes')),
            ],
        ),
        migrations.CreateModel(
            name='Componenetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ingredientes', models.ManyToManyField(to='polls.ingredientes')),
            ],
        ),
    ]
