# Generated by Django 4.2 on 2023-05-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Componenetes',
            new_name='Componenete',
        ),
        migrations.RenameModel(
            old_name='Ingredientes',
            new_name='Ingrediente',
        ),
    ]
