# Generated by Django 4.2 on 2023-05-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_componenetes_componenete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenete',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
    ]
