# Generated by Django 4.2 on 2023-05-16 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_componenete_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('desconto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField()),
                ('componenetes', models.ManyToManyField(to='polls.componenete')),
            ],
        ),
        migrations.AddField(
            model_name='sorvete',
            name='imagem',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('produtos', models.ManyToManyField(to='polls.produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='sorvete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.sorvete'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tigela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.tigela'),
        ),
    ]
