# Generated by Django 4.2 on 2023-05-16 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_cupom_produto_sorvete_imagem_venda_produto_sorvete_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Componenete',
            new_name='Componente',
        ),
    ]
