# Generated by Django 4.2 on 2023-06-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_componenete_componente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorvete',
            name='descricao',
            field=models.CharField(default=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='produto',
            name='componenetes',
            field=models.ManyToManyField(default=True, to='polls.componente'),
        ),
        migrations.AlterField(
            model_name='sorvete',
            name='estoque',
            field=models.FloatField(help_text='qtd em Litros'),
        ),
        migrations.AlterField(
            model_name='sorvete',
            name='ingredientes',
            field=models.ManyToManyField(default=True, to='polls.ingrediente'),
        ),
        migrations.AlterField(
            model_name='sorvete',
            name='marca',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sorvete',
            name='preco',
            field=models.FloatField(help_text='preço em MiliLitros'),
        ),
    ]
