# Generated by Django 4.2 on 2023-06-24 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_alter_sorvete_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.AddField(
            model_name='produto',
            name='cliente_id',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente_id',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sorvete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sorvete'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tigela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tigela'),
        ),
    ]
