# Generated by Django 4.2 on 2023-06-24 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0008_remove_produto_preco_produto_cliente_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cliente_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
