# Generated by Django 4.2 on 2023-06-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_produto_cliente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='componenetes',
            new_name='componentes',
        ),
    ]
