# Generated by Django 4.2 on 2023-06-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_rename_componenetes_produto_componentes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='cliente_id',
            new_name='cliente',
        ),
    ]
