# Generated by Django 4.2 on 2023-06-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rename_cliente_id_produto_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cupom',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='ingredientes',
        ),
    ]
