# Generated by Django 4.2 on 2023-06-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_venda_produtos_relacaoprodutovenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(through='polls.RelacaoProdutoVenda', to='polls.produto'),
        ),
    ]
