# Generated by Django 4.2 on 2023-06-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_venda_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacaoprodutovenda',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.produto'),
        ),
    ]
